version: '3'
services:
  mysql:
    build:
      context: ./mysql
    platform: linux/x86_64   # M1 Mac
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/docs:/docs
    working_dir: /docs
    environment:
      MYSQL_ROOT_PASSWORD: tobitabm!
      MYSQL_USER: tooluser
      MYSQL_PASSWORD: tobitabm2
      MYSQL_DATABASE: bookmaker
      # タイムゾーンはJSTで統一
      TZ: Asia/Tokyo
      MYSQL_ROOT_HOST: "%"
    container_name: tob-mysql
  redis:
    image: "redis:4-alpine"
    ports:
      - "6379:6379"
    container_name: tob-redis
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tobitabm!
    ports:
      - 8080:80
    container_name: phpmyadmin_tobitas
  apache-cms:
    container_name: apache-cms
    build:
      context: ./php-apache-cms
    ports:
        - '8888:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
  